dist: xenial

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key CAEB3DC3BDF7FB45
  - echo "deb https://qgis.org/ubuntugis xenial main" | sudo tee -a /etc/apt/sources.list
  - sudo apt update
  - sudo apt install qgis python-qgis

language: python

python:
  - "3.4"
  - "3.5"

install:
  - "export PYTHONPATH=$PYTHONPATH:/usr/share/qgis/python"
  - "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/share/qgis/lib"

script:
  - python3 app.py

