dist: xenial

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key CAEB3DC3BDF7FB45
  - echo "deb https://qgis.org/ubuntugis xenial main" | sudo tee -a /etc/apt/sources.list
  - sudo apt update
  - sudo apt install qgis python-qgis
  - pip install --upgrade pip

language: python

python:
  - "3.4"
  - "3.5"

before_script:
  - export PYTHONPATH=/usr/share/qgis/python
  - export LD_LIBRARY_PATH=/usr/lib
  - export PATH=$PATH:$PYTHONPATH
  - printenv

script:
  - python app.py
