dist: bionic

before_install:
  - echo "deb https://qgis.org/ubuntu bionic main" | sudo tee -a /etc/apt/sources.list
  - sudo apt update
  - sudo apt install qgis
  - pip install --upgrade pip
  - sudo apt install python3-tk
  - sudo apt install xvfb
  - pip install scikit-learn
 
language: python

python:
  - "3.7"


before_script:
  - which qgis
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - echo "PYTHONPATH:" $PYTHONPATH
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib

script:
  - which python
  - xvfb-run -a python app.py
